// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/order"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/staffmember"
)

// StaffMemberQuery is the builder for querying StaffMember entities.
type StaffMemberQuery struct {
	config
	ctx                 *QueryContext
	order               []staffmember.OrderOption
	inters              []Interceptor
	predicates          []predicate.StaffMember
	withProcessedOrders *OrderQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StaffMemberQuery builder.
func (smq *StaffMemberQuery) Where(ps ...predicate.StaffMember) *StaffMemberQuery {
	smq.predicates = append(smq.predicates, ps...)
	return smq
}

// Limit the number of records to be returned by this query.
func (smq *StaffMemberQuery) Limit(limit int) *StaffMemberQuery {
	smq.ctx.Limit = &limit
	return smq
}

// Offset to start from.
func (smq *StaffMemberQuery) Offset(offset int) *StaffMemberQuery {
	smq.ctx.Offset = &offset
	return smq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smq *StaffMemberQuery) Unique(unique bool) *StaffMemberQuery {
	smq.ctx.Unique = &unique
	return smq
}

// Order specifies how the records should be ordered.
func (smq *StaffMemberQuery) Order(o ...staffmember.OrderOption) *StaffMemberQuery {
	smq.order = append(smq.order, o...)
	return smq
}

// QueryProcessedOrders chains the current query on the "processed_orders" edge.
func (smq *StaffMemberQuery) QueryProcessedOrders() *OrderQuery {
	query := (&OrderClient{config: smq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := smq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := smq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(staffmember.Table, staffmember.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, staffmember.ProcessedOrdersTable, staffmember.ProcessedOrdersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(smq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first StaffMember entity from the query.
// Returns a *NotFoundError when no StaffMember was found.
func (smq *StaffMemberQuery) First(ctx context.Context) (*StaffMember, error) {
	nodes, err := smq.Limit(1).All(setContextOp(ctx, smq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{staffmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smq *StaffMemberQuery) FirstX(ctx context.Context) *StaffMember {
	node, err := smq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StaffMember ID from the query.
// Returns a *NotFoundError when no StaffMember ID was found.
func (smq *StaffMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(1).IDs(setContextOp(ctx, smq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{staffmember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smq *StaffMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := smq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StaffMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StaffMember entity is found.
// Returns a *NotFoundError when no StaffMember entities are found.
func (smq *StaffMemberQuery) Only(ctx context.Context) (*StaffMember, error) {
	nodes, err := smq.Limit(2).All(setContextOp(ctx, smq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{staffmember.Label}
	default:
		return nil, &NotSingularError{staffmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smq *StaffMemberQuery) OnlyX(ctx context.Context) *StaffMember {
	node, err := smq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StaffMember ID in the query.
// Returns a *NotSingularError when more than one StaffMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (smq *StaffMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(2).IDs(setContextOp(ctx, smq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{staffmember.Label}
	default:
		err = &NotSingularError{staffmember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smq *StaffMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := smq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StaffMembers.
func (smq *StaffMemberQuery) All(ctx context.Context) ([]*StaffMember, error) {
	ctx = setContextOp(ctx, smq.ctx, "All")
	if err := smq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StaffMember, *StaffMemberQuery]()
	return withInterceptors[[]*StaffMember](ctx, smq, qr, smq.inters)
}

// AllX is like All, but panics if an error occurs.
func (smq *StaffMemberQuery) AllX(ctx context.Context) []*StaffMember {
	nodes, err := smq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StaffMember IDs.
func (smq *StaffMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if smq.ctx.Unique == nil && smq.path != nil {
		smq.Unique(true)
	}
	ctx = setContextOp(ctx, smq.ctx, "IDs")
	if err = smq.Select(staffmember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smq *StaffMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := smq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smq *StaffMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, smq.ctx, "Count")
	if err := smq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, smq, querierCount[*StaffMemberQuery](), smq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (smq *StaffMemberQuery) CountX(ctx context.Context) int {
	count, err := smq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smq *StaffMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, smq.ctx, "Exist")
	switch _, err := smq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (smq *StaffMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := smq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StaffMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smq *StaffMemberQuery) Clone() *StaffMemberQuery {
	if smq == nil {
		return nil
	}
	return &StaffMemberQuery{
		config:              smq.config,
		ctx:                 smq.ctx.Clone(),
		order:               append([]staffmember.OrderOption{}, smq.order...),
		inters:              append([]Interceptor{}, smq.inters...),
		predicates:          append([]predicate.StaffMember{}, smq.predicates...),
		withProcessedOrders: smq.withProcessedOrders.Clone(),
		// clone intermediate query.
		sql:  smq.sql.Clone(),
		path: smq.path,
	}
}

// WithProcessedOrders tells the query-builder to eager-load the nodes that are connected to
// the "processed_orders" edge. The optional arguments are used to configure the query builder of the edge.
func (smq *StaffMemberQuery) WithProcessedOrders(opts ...func(*OrderQuery)) *StaffMemberQuery {
	query := (&OrderClient{config: smq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	smq.withProcessedOrders = query
	return smq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StaffMember.Query().
//		GroupBy(staffmember.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (smq *StaffMemberQuery) GroupBy(field string, fields ...string) *StaffMemberGroupBy {
	smq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StaffMemberGroupBy{build: smq}
	grbuild.flds = &smq.ctx.Fields
	grbuild.label = staffmember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.StaffMember.Query().
//		Select(staffmember.FieldName).
//		Scan(ctx, &v)
func (smq *StaffMemberQuery) Select(fields ...string) *StaffMemberSelect {
	smq.ctx.Fields = append(smq.ctx.Fields, fields...)
	sbuild := &StaffMemberSelect{StaffMemberQuery: smq}
	sbuild.label = staffmember.Label
	sbuild.flds, sbuild.scan = &smq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StaffMemberSelect configured with the given aggregations.
func (smq *StaffMemberQuery) Aggregate(fns ...AggregateFunc) *StaffMemberSelect {
	return smq.Select().Aggregate(fns...)
}

func (smq *StaffMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range smq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, smq); err != nil {
				return err
			}
		}
	}
	for _, f := range smq.ctx.Fields {
		if !staffmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smq.path != nil {
		prev, err := smq.path(ctx)
		if err != nil {
			return err
		}
		smq.sql = prev
	}
	return nil
}

func (smq *StaffMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StaffMember, error) {
	var (
		nodes       = []*StaffMember{}
		_spec       = smq.querySpec()
		loadedTypes = [1]bool{
			smq.withProcessedOrders != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StaffMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StaffMember{config: smq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := smq.withProcessedOrders; query != nil {
		if err := smq.loadProcessedOrders(ctx, query, nodes,
			func(n *StaffMember) { n.Edges.ProcessedOrders = []*Order{} },
			func(n *StaffMember, e *Order) { n.Edges.ProcessedOrders = append(n.Edges.ProcessedOrders, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (smq *StaffMemberQuery) loadProcessedOrders(ctx context.Context, query *OrderQuery, nodes []*StaffMember, init func(*StaffMember), assign func(*StaffMember, *Order)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*StaffMember)
	nids := make(map[int]map[*StaffMember]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(staffmember.ProcessedOrdersTable)
		s.Join(joinT).On(s.C(order.FieldID), joinT.C(staffmember.ProcessedOrdersPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(staffmember.ProcessedOrdersPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(staffmember.ProcessedOrdersPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*StaffMember]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Order](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "processed_orders" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (smq *StaffMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smq.querySpec()
	_spec.Node.Columns = smq.ctx.Fields
	if len(smq.ctx.Fields) > 0 {
		_spec.Unique = smq.ctx.Unique != nil && *smq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, smq.driver, _spec)
}

func (smq *StaffMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(staffmember.Table, staffmember.Columns, sqlgraph.NewFieldSpec(staffmember.FieldID, field.TypeInt))
	_spec.From = smq.sql
	if unique := smq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if smq.path != nil {
		_spec.Unique = true
	}
	if fields := smq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, staffmember.FieldID)
		for i := range fields {
			if fields[i] != staffmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := smq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smq *StaffMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smq.driver.Dialect())
	t1 := builder.Table(staffmember.Table)
	columns := smq.ctx.Fields
	if len(columns) == 0 {
		columns = staffmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smq.sql != nil {
		selector = smq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smq.ctx.Unique != nil && *smq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range smq.predicates {
		p(selector)
	}
	for _, p := range smq.order {
		p(selector)
	}
	if offset := smq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StaffMemberGroupBy is the group-by builder for StaffMember entities.
type StaffMemberGroupBy struct {
	selector
	build *StaffMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smgb *StaffMemberGroupBy) Aggregate(fns ...AggregateFunc) *StaffMemberGroupBy {
	smgb.fns = append(smgb.fns, fns...)
	return smgb
}

// Scan applies the selector query and scans the result into the given value.
func (smgb *StaffMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, smgb.build.ctx, "GroupBy")
	if err := smgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StaffMemberQuery, *StaffMemberGroupBy](ctx, smgb.build, smgb, smgb.build.inters, v)
}

func (smgb *StaffMemberGroupBy) sqlScan(ctx context.Context, root *StaffMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(smgb.fns))
	for _, fn := range smgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*smgb.flds)+len(smgb.fns))
		for _, f := range *smgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*smgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StaffMemberSelect is the builder for selecting fields of StaffMember entities.
type StaffMemberSelect struct {
	*StaffMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sms *StaffMemberSelect) Aggregate(fns ...AggregateFunc) *StaffMemberSelect {
	sms.fns = append(sms.fns, fns...)
	return sms
}

// Scan applies the selector query and scans the result into the given value.
func (sms *StaffMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sms.ctx, "Select")
	if err := sms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StaffMemberQuery, *StaffMemberSelect](ctx, sms.StaffMemberQuery, sms, sms.inters, v)
}

func (sms *StaffMemberSelect) sqlScan(ctx context.Context, root *StaffMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sms.fns))
	for _, fn := range sms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
