// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CartItem is the predicate function for cartitem builders.
type CartItem func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
